#!/usr/bin/env python3
"""Extract city light sources from NASA Earth at Night raster texture.

Analyzes the NASA city_lights.png texture to automatically identify all
significant light sources (cities, towns, settlements, road corridors)
and outputs a Dart data file with their positions and intensities.

Usage:
    python3 scripts/extract_city_lights.py

Reads:  assets/textures/city_lights.png (4096x2048 NASA Earth at Night)
Writes: lib/game/rendering/city_lights_extracted.dart
"""

import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

# --- Configuration ---
BLOCK_SIZE = 32        # Pixels per grid cell (32x32 → 128x64 grid)
MAX_POINTS = 1500      # Maximum light points to extract
NOISE_FLOOR = 12       # Background brightness to subtract (from ocean analysis)
MIN_BRIGHTNESS = 1.0   # Minimum adjusted brightness to include
POLAR_LAT = 65.0       # Latitude beyond which to apply polar penalty
POLAR_PENALTY = 0.15   # Multiply polar brightness by this (ice/aurora artifacts)

# --- Paths ---
SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent
INPUT_PATH = PROJECT_DIR / "assets" / "textures" / "city_lights.png"
OUTPUT_PATH = (
    PROJECT_DIR / "lib" / "game" / "rendering" / "city_lights_extracted.dart"
)


def extract_lights(img: Image.Image) -> list[tuple[float, float, float]]:
    """Extract light sources from NASA texture using grid-based analysis.

    Divides the image into BLOCK_SIZE x BLOCK_SIZE cells, computes mean
    brightness per cell, and returns the brightest cells as (lat, lon, intensity).
    """
    w, h = img.size
    grid_w = w // BLOCK_SIZE
    grid_h = h // BLOCK_SIZE
    print(f"  Image: {w}x{h}")
    print(f"  Grid: {grid_w}x{grid_h} = {grid_w * grid_h} cells "
          f"(block size {BLOCK_SIZE}x{BLOCK_SIZE})")

    cells: list[tuple[float, float, float]] = []

    for gy in range(grid_h):
        for gx in range(grid_w):
            total_brightness = 0.0
            pixel_count = 0

            for dy in range(BLOCK_SIZE):
                for dx in range(BLOCK_SIZE):
                    px = gx * BLOCK_SIZE + dx
                    py = gy * BLOCK_SIZE + dy
                    r, g, b = img.getpixel((px, py))[:3]
                    total_brightness += max(r, g, b)
                    pixel_count += 1

            avg_brightness = total_brightness / pixel_count
            adjusted = avg_brightness - NOISE_FLOOR
            # Convert grid cell center to lat/lon (equirectangular)
            lon = (gx + 0.5) / grid_w * 360.0 - 180.0
            lat = 90.0 - (gy + 0.5) / grid_h * 180.0

            # Penalize polar regions — ice/aurora create false brightness
            abs_lat = abs(lat)
            if abs_lat > POLAR_LAT:
                polar_factor = POLAR_PENALTY
                adjusted *= polar_factor

            if adjusted < MIN_BRIGHTNESS:
                continue

            cells.append((adjusted, lat, lon))

    # Sort by brightness descending
    cells.sort(key=lambda c: c[0], reverse=True)

    # Take top MAX_POINTS
    top = cells[:MAX_POINTS]

    # Normalize intensities to 0.0–1.0 (relative to brightest)
    if not top:
        return []
    max_brightness = top[0][0]
    result = [
        (lat, lon, round(brightness / max_brightness, 4))
        for brightness, lat, lon in top
    ]

    print(f"  Total cells above noise floor: {len(cells)}")
    print(f"  Extracted top {len(result)} light sources")
    if result:
        print(f"  Brightest: {top[0][0]:.1f} (raw), dimmest kept: "
              f"{top[-1][0]:.1f} (raw)")

    return result


def write_dart_file(lights: list[tuple[float, float, float]]) -> None:
    """Write extracted lights to a Dart source file."""
    lines = [
        "/// Auto-extracted city light sources from NASA Earth at Night.",
        "///",
        "/// Generated by `scripts/extract_city_lights.py`.",
        f"/// {len(lights)} light sources from {BLOCK_SIZE}x{BLOCK_SIZE} "
        "block grid analysis.",
        "///",
        "/// Each entry: [latitude, longitude, intensity]",
        "/// - latitude: -90 (south pole) to +90 (north pole)",
        "/// - longitude: -180 (west) to +180 (east)",
        "/// - intensity: 0.0 (dimmest) to 1.0 (brightest), normalized",
        "///",
        "/// Source: NASA Earth at Night (Public Domain)",
        "/// https://earthobservatory.nasa.gov/features/NightLights",
        f"const List<List<double>> extractedCityLights = [",
    ]

    for lat, lon, intensity in lights:
        lines.append(f"  [{lat:.2f}, {lon:.2f}, {intensity}],")

    lines.append("];")
    lines.append("")  # trailing newline

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"  Written to: {OUTPUT_PATH.relative_to(PROJECT_DIR)}")


def main() -> None:
    print("Extracting city lights from NASA texture...")

    if not INPUT_PATH.exists():
        print(f"ERROR: Input file not found: {INPUT_PATH}")
        sys.exit(1)

    img = Image.open(INPUT_PATH)
    lights = extract_lights(img)
    write_dart_file(lights)
    print("Done.")


if __name__ == "__main__":
    main()
